name: codbex - Build Application Module
description: Build NPM packages from an application module
author: codbex

branding:
    icon: package
    color: orange

inputs:
    packages:
        description: List of package paths to build
        required: true
    npmrc:
        description: .npmrc config file content
        required: false
    publish:
        description: Whether to publish the NPM packages
        default: 'false'
    publish-latest-version:
        description: Whether to add the commit SHAT to the version (e.g. 1.0.0-8bb4b5b9c3eb08b81b1be0fb2c533237c5cb5abb)
        default: 'false'

runs:
    using: node20
    main: dist/index.js
