name: codbex - Build Modules
description: Build NPM packages from an application model
author: codbex

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
    icon: heart
    color: red

# Define your inputs here.
inputs:
    packages-build:
        description: List of package paths to build
        required: true
    npmrc:
        description: .npmrc config file content
        required: false

runs:
    using: node20
    main: dist/index.js
